### ISSUE TITLE
Ssh git with port issue

### ISSUE THREAD

**Issue by fokot** [coralogix/protofetch#127]
I add ssh keys with 
```
 ssh-add ~/.ssh/xxx_ed25519  
```
Protofetch fails, while `protodep up` works
```
$ protofetch fetch
INFO Resolving git.xxx.online:2222/xxx/xxx-grpc-api
ERROR Git error: remote rejected authentication: Failed getting response; class=Ssh (23); code=Auth (-16)
```

 
I can ssh to server, it is private gitlab
```
ssh -T git@git.xxx.online -p 2222
```
Can the port be a problem?

**Comment by rtimush** [comment]
It's quite possible that custom ssh ports are not supported, although when I try to explicitly specify port 22 for github, it fails after the auth, so maybe there is more than one issue.

**Comment by fokot** [comment]
That might be the issue, that everytime the port is specified, it is interpreted wrongly.

**Comment by rtimush** [comment]
@fokot Would be great if you could check if https://github.com/coralogix/protofetch/pull/128 helps (for me it works for URLs like github.com:22/org/repo with this change).

**Comment by rtimush** [comment]
@fokot I cannot reproduce either of these issues, could you please create a separate issue with the content your `protodep.toml`/`protofetch.toml` (possibly sanitized from any private stuff)?
