### ISSUE TITLE
Maybe standardize quotes in lockfiles

### ISSUE THREAD

**Issue by eliduvid** [coralogix/protofetch#129]
Depending on dev environment (or phases of the moon, idk) of each dev, the lockfile is generated with single or double quotes. So nearly every commit contains change to the lockfile.
Is there an option to standardize it some one way? Or perhaps add a param to do it?

**Comment by rtimush** [comment]
I'm pretty sure the quotes style changed when we updated the `toml` dependency in 0.0.22. All v2 lock files should have consistent quotes style.

**Comment by eliduvid** [comment]
OK, will check. Maybe it's just outdated versions on dev machines
