### ISSUE TITLE
Use revisions(hashes) out of master

### ISSUE THREAD

**Issue by kakoc** [coralogix/protofetch#146]
Hi 👋,

I have the following use case:
I need to develop something on the BE, lets say add another grpc method. For such grpc service contracts we have some separate repository. Now the actual repository which implements that contract should pull that repository with grpc contracts. Since I'm still developing, that contract api isn't merged into master(I want to test it end to end first). So If I'm trying to refer to that commit(with new contract api) from the service which implements that api using commit's hash it doesn't work work for me(it tells that it can't find such commit. As I see the main problem is that it searches commits inside master maybe?). Another option which works for me is to use branch name instead, but in such cases if I update that branch with the new content it won't be pulled again(probably since branch already pulled).
So can we improve a workflow and make possible to refer to commits through a hash which is not inside master? Or maybe I just misusing that tool in some way?
Thanks for the tool!

**Comment by rtimush** [comment]
Hi @kakoc! The recommended approach would be to specify the branch name in the `protofetch.toml` file, and run `protofetch update` whenever you want to get the latest commit from this branch.

Alternatively, it should be possible to specify both `branch` and `revision`. This approach is in my opinion less convenient, and it has some limitations in more complex dependency graphs, but nevertheless it should work.

**Comment by kakoc** [comment]
> Hi @kakoc! The recommended approach would be to specify the branch name in the `protofetch.toml` file, and run `protofetch update` whenever you want to get the latest commit from this branch.
> 
> Alternatively, it should be possible to specify both `branch` and `revision`. This approach is in my opinion less convenient, and it has some limitations in more complex dependency graphs, but nevertheless it should work.

Thanks for the suggestion! 
Looks fine to me.
