### ISSUE TITLE
Make protofetch usable from cargo build scripts

### ISSUE THREAD

**Issue by rtimush** [coralogix/protofetch#39]
Currently, if you want to use protofetch for a Rust project, you have to execute it as a binary tool. It would be nice to have a Rust API that can be used in `build.rs` directly.

**Comment by mkatychev** [comment]
what's the status on this issue? https://docs.rs/protofetch/latest/protofetch/fetch/fn.fetch_sources.html this looks like a valid way to use from `build.rs`.
